### ISSUE TITLE
New flag needed in Vagrantfile to avoid ssh lockout

### ISSUE THREAD

**Issue by bbaassssiiee** [defunctzombie/coreos-ansible-example#6]
Add this:
    config.ssh.insert_key = false

Reference:
https://github.com/coreos/docs/issues/10

**Comment by Quintasan** [comment]
Alternatively I believe one could use the key that Vagrant generates upon issuing vagrant up. The key is located under:
```
`pwd`/.vagrant/machines/core-01/virtualbox/private_key
```
